{
 "title": "Locust test",
 "description": "Locust Exporter - Container Solutions",
 "tags": [ "locust" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Locust Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "locust_running" }
   ]
  },
  {
   "title": "Swarmed users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "locust_users" }
   ]
  },
  {
   "title": "Current RPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "locust_requests_current_rps{name=\"Aggregated\"}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "locust_requests_num_requests{method=~\"\"}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Fails",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(locust_requests_fail_ratio)"
    }
   ]
  },
  {
   "title": "Connected workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "locust_workers_count" }
   ]
  },
  {
   "title": "Failers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "locust_requests_num_failures{method=~\"\"}"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(locust_requests_avg_content_length{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_min_response_time{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_max_response_time{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_avg_response_time{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_median_response_time{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_num_failures{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_current_fail_per_sec{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_num_requests{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_current_rps{method=~\".+\"}) by (method, name)"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(locust_requests_max_response_time)",
     "legendFormat": "AVG MAX"
    },
    {
     "expr": "avg(locust_requests_min_response_time)",
     "legendFormat": "AVG MIN"
    },
    {
     "expr": "avg(locust_requests_avg_response_time)",
     "legendFormat": "AVG AVG"
    },
    {
     "expr": "avg(locust_requests_median_response_time)",
     "legendFormat": "AVG MEDIAN"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "locust_requests_current_response_time_percentile_95",
     "legendFormat": "P95"
    },
    {
     "expr": "locust_requests_current_response_time_percentile_50",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Requests per endpoint / s",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(locust_requests_num_requests{method=~\".+\"}[1m])",
     "legendFormat": "{{ method}} - {{name}}"
    },
    {
     "expr": " sum(rate(locust_requests_num_requests{method=~\".+\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "locust_requests_fail_ratio * 100",
     "legendFormat": "fail_ratio [%]"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(locust_errors) by (method, name, error)"
    }
   ]
  }
 ]
}